### ISSUE TITLE
'rentmybike.settings.custom' not found

### ISSUE THREAD

**Issue by mjallday** [balanced/rentmybikes#1]
https://gist.github.com/juanfiguera/5120505

```
17:22:28 web.1     | Traceback (most recent call last):
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/gunicorn/arbiter.py", line 469, in spawn_worker
17:22:28 web.1     |     worker.init_process()
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/gunicorn/workers/base.py", line 100, in init_process
17:22:28 web.1     |     self.wsgi = self.app.wsgi()
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/gunicorn/app/base.py", line 99, in wsgi
17:22:28 web.1     |     self.callable = self.load()
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 24, in load
17:22:28 web.1     |     return util.import_app(self.app_uri)
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/gunicorn/util.py", line 287, in import_app
17:22:28 web.1     |     __import__(module)
17:22:28 web.1     |   File "/Users/juanfiguera/Projects/rentmybikes/rentmybike/__init__.py", line 16, in <module>
17:22:28 web.1     |     config.from_object('rentmybike.settings.custom')
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/flask/config.py", line 163, in from_object
17:22:28 web.1     |     obj = import_string(obj)
17:22:28 web.1     |   File "/Users/juanfiguera/.virtualenvs/rentmybike/lib/python2.7/site-packages/werkzeug/utils.py", line 422, in import_string
17:22:28 web.1     |     __import__(modname)
17:22:28 web.1     | ImportStringError: import_string() failed for 'rentmybike.settings.custom'. Possible reasons are:
17:22:28 web.1     | 
17:22:28 web.1     | - missing __init__.py in a package;
17:22:28 web.1     | - package or module path not included in sys.path;
17:22:28 web.1     | - duplicated package or module name taking precedence in sys.path;
17:22:28 web.1     | - missing module, class, function or variable;
17:22:28 web.1     | 
17:22:28 web.1     | Debugged import:
17:22:28 web.1     | 
17:22:28 web.1     | - 'rentmybike' found in '/Users/juanfiguera/Projects/rentmybikes/rentmybike/__init__.py'.
17:22:28 web.1     | - 'rentmybike.settings' found in '/Users/juanfiguera/Projects/rentmybikes/rentmybike/settings/__init__.py'.
17:22:28 web.1     | - 'rentmybike.settings.custom' not found.
17:22:28 web.1     | 
17:22:28 web.1     | Original exception:
17:22:28 web.1     | 
17:22:28 web.1     | ImportError: No module named custom
17:22:28 web.1     | 2013-03-08 17:22:28 [58981] [INFO] Worker exiting (pid: 58981)
17:22:28 web.1     | 2013-03-08 17:22:28 [58980] [INFO] Shutting down: Master
17:22:28 web.1     | 2013-03-08 17:22:28 [58980] [INFO] Reason: Worker failed to boot.
17:22:28 web.1     | process terminated
```

**Comment by bninja** [comment]
should work out the box now!
