### ISSUE TITLE
When emailing receipt as a logged in user, I get this error message when attempting to rent a bike

### ISSUE THREAD

**Issue by mahmoudimus** [balanced/rentmybikes#2]
Oops

``` python

    Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<string>", line 2, in update
  File "/app/rentmybike/controllers/__init__.py", line 83, in validation_func
    return function(*args, forms=existing_forms, **kwargs)
  File "<string>", line 2, in update
  File "/app/rentmybike/controllers/__init__.py", line 83, in validation_func
    return function(*args, forms=existing_forms, **kwargs)
  File "/app/rentmybike/controllers/rent.py", line 130, in update
    charge=balanced.Transaction.find(rental.debit_uri)
  File "/app/rentmybike/email.py", line 36, in send_email
    current_app.emailer.send(msg)
  File "/app/.heroku/python/lib/python2.7/site-packages/flaskext/mail/__init__.py", line 96, in send
    message.send(connection)
  File "/app/.heroku/python/lib/python2.7/site-packages/flaskext/mail/message.py", line 131, in send
    assert self.sender, "No sender address has been set"
AssertionError: No sender address has been set
```

**Comment by mahmoudimus** [comment]
Fixed in 359fe00
